name: Lint & test & build

on: push

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.5
          cache: false

      - name: Generate
        run: |-
          go get -u -t github.com/tinylib/msgp
          go install github.com/tinylib/msgp
          make gen

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.55.2
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.5
          cache: false

      - name: Generate
        run: |-
          go get -u -t github.com/tinylib/msgp
          go install github.com/tinylib/msgp
          make gen

  #      - name: Test
  #        run: make test
  #        env:
  #          CFG_PATH: ./conf/config.github.json
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/swup:http-0.0.6
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/swup:http-latest
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/swup:http-latest,mode=max
